{{- if (.Values.installNamespace) -}}
---
###
### Linkerd Namespace
###
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Release.namespace }}
  annotations:
    {{.Values.global.proxyInjectAnnotation}}: {{.Values.global.proxyInjectDisabled}}
  labels:
    {{.Values.global.linkerdNamespaceLabel}}: "true"
    config.linkerd.io/admission-webhooks: disabled
    {{.Values.global.controllerNamespaceLabel}}: {{.Release.namespace}}
{{ end -}}
